### ISSUE TITLE
How to install Node and NPM packages with Vite

### ISSUE THREAD

**Issue by anuzpandey** [render-examples/php-laravel-docker#39]
I am running Laravel 10 application. Everything is working I guess but I have an error "Vite manifest file is not found".
How do I install node and npm, and run npm scripts?

Thank you in advance.

**Comment by lombervid** [comment]
Adding this to `Dockerfile` worked for me:
```bash
RUN apk add --update nodejs npm
```

And then adding a script file to `scripts` folder to execute `npm install` as commented here:
https://github.com/render-examples/php-laravel-docker/issues/26#issuecomment-1657330119
